// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX8nsdYewR5UBN9NbP3AZQt3LtLrdd4uk',
    appId: '1:570937298347:web:c069180c1799f4c9a896ee',
    messagingSenderId: '570937298347',
    projectId: 'social-app-myproject',
    authDomain: 'social-app-myproject.firebaseapp.com',
    storageBucket: 'social-app-myproject.firebasestorage.app',
    measurementId: 'G-KEZ5VSRNH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJG7Z9FJaNT7M3-Aef20bfOFr0bjGLYw',
    appId: '1:570937298347:android:40cfeee5048add77a896ee',
    messagingSenderId: '570937298347',
    projectId: 'social-app-myproject',
    storageBucket: 'social-app-myproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdLPAejUNU0FA7bFLrm0mcKQvTIm12kmQ',
    appId: '1:570937298347:ios:465c1113c5f8f4c1a896ee',
    messagingSenderId: '570937298347',
    projectId: 'social-app-myproject',
    storageBucket: 'social-app-myproject.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdLPAejUNU0FA7bFLrm0mcKQvTIm12kmQ',
    appId: '1:570937298347:ios:465c1113c5f8f4c1a896ee',
    messagingSenderId: '570937298347',
    projectId: 'social-app-myproject',
    storageBucket: 'social-app-myproject.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX8nsdYewR5UBN9NbP3AZQt3LtLrdd4uk',
    appId: '1:570937298347:web:6b8a7a9ae5ccd646a896ee',
    messagingSenderId: '570937298347',
    projectId: 'social-app-myproject',
    authDomain: 'social-app-myproject.firebaseapp.com',
    storageBucket: 'social-app-myproject.firebasestorage.app',
    measurementId: 'G-7PX15GEBK8',
  );
}
